name       : python-slip
version    : 0.4.1
release    : 1
source     :
    - https://github.com/nphilipp/python-slip/releases/download/python-slip-0.4.1/python-slip-0.4.1.tar.bz2 : 12a9e01420a10527ce1f05567b6185f98acaeafec7b389540f7706f144f93cf8
license    : GPL-2.0
component  : programming.python
summary    : Convenience module for Python 2 Projects
description: |
    Convenience, extension and workaround code for Python and some Python modules.
builddeps  :
    - pkgconfig(python-2.7)
    - python-setuptools
rundeps    :
    - python-dbus
    - python-decorator
build      : |
    %make
install    : |
    %make_install
